import Head from 'next/head';
import { Inter } from 'next/font/google';
import Landing from '../components/Landing';
import List from '../components/List';
import Location from '../components/Location';
import axios from "axios";
import { useState } from 'react';
import Add from '../components/Add';
import { useRouter } from 'next/router';
import AddButton from '../components/AddButton';



const inter = Inter({ subsets: ['latin'] })

export default function Home({list, admin}) {
  const [close, setClose] = useState(true);
  
  const router = useRouter();

useEffect(() => {
const handleRouteChange = (url) => {
sessionStorage.setItem(`scroll-position-${router.pathname}`, window.scrollY);
};
router.events.on('routeChangeStart', handleRouteChange);

return () => {
  router.events.off('routeChangeStart', handleRouteChange);
};
}, []);

useEffect(() => {
  const scrollPosition = sessionStorage.getItem(`scroll-position-${router.pathname}`);
  if (scrollPosition) {
  window.scrollTo(0, parseInt(scrollPosition));
  }
  }, []);

  return (
    <>
      <Head>
        <title>Smash Burger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/imgs/ico.png" />
        <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet"></link>
        <meta charSet='utf-8' />
      </Head>
      <Landing />
      {admin && <AddButton setClose={setClose}/> }
      <List list={list} />
      {!close && <Add setClose={setClose}/> }
      <Location />
      {/* <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
      <script>
  AOS.init();
</script> */}
    </>
  )
}

export const getServerSideProps = async (ctx) => {
  const myCookie = ctx.req?.cookies || "";
  let admin = false;

  if (myCookie.token === process.env.TOKEN) {
    admin = true;
  }



  const res = await axios.get("https://smash-suez0.vercel.app/api/products");
  return{
    props:{
      list: res.data,
      admin
    }
  }
}
